app/urls.py
from django.urls import path
from .views import index,logout_user,signup_user,login_user,create

from django.conf import settings
from django.conf.urls.static import static

app_name='app'

urlpatterns = [
    path('',index,name='index'),
    path('sign',signup_user,name="sign"),
    path('login',login_user,name="login"),
    path('logout',logout_user,name="logout"),
    path('create',create,name="create"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    #additional
    dob=models.DateField()
    gender=models.BooleanField(choices=[(False,'Male'),(True,'Female')],default=False)
    profile_pic=models.ImageField(upload_to='profile',default="../static/img6Q.png",blank=True)
    def __str__(self):
        return "{0} {1}".format(self.user.first_name,self.user.last_name)

app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile

class UserForm(forms.ModelForm):
    cpassword=forms.CharField(label='Confirm Password',widget=forms.PasswordInput())
    def clean(self):
        usr=super().clean()
        if(usr['password']!=usr['cpassword']):
            raise forms.ValidationError("Passwords do not match!")
    class Meta():
        model=User
        fields = ('first_name','last_name','email','username','password','cpassword')
        widgets = {
            'first_name':forms.TextInput(),
            'last_name':forms.TextInput(),
            'email':forms.EmailInput(),
            'username':forms.TextInput(),
            'password':forms.PasswordInput()
        }


class UserProfileForm(forms.ModelForm):
    class Meta():
        model=UserProfile
        fields = ('dob','gender','profile_pic')
        labels={
            'dob':'DOB',
            'gender':'Gender',
            'profile_pic':'Profile Picture'
        }
        widgets={
            'dob':forms.DateInput(format=('%d-%m-%Y'),attrs={'type': 'date'}),
            'gender':forms.Select(choices=((False,'Male'),(True,'Female'))),
            'profile_pic':forms.FileInput(),
        }

app/views.py
from django.shortcuts import render
from time import sleep
from .models import UserProfile
from .forms import UserForm,UserProfileForm

#login imports
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect
from django.urls import reverse 
from django.contrib.auth.decorators import login_required

def index(request):
    if(request.user.is_authenticated):
        user_profile_pic=UserProfile.objects.get(user=request.user).profile_pic
        return render(request,"index.html",{'pic':user_profile_pic})
    sleep(1)
    return render(request,"index.html",{'pic':None})

'''
This save() method accepts an optional commit keyword argument, which accepts either True or False. 
If you call save() with commit=False, then it will return an object that hasn’t yet been saved to the database. 
In this case, it’s up to you to call save() on the resulting model instance. 
This is useful if you want to do custom processing on the object before saving it
'''
def signup_user(request):
    if(request.method=='POST'):
        user_form=UserForm(request.POST)
        user_profile_form=UserProfileForm(request.POST,request.FILES)
        if(user_form.is_valid() and user_profile_form.is_valid()):
            user=user_form.save()
            user.set_password(user.password)
            user.save()
            user_profile=user_profile_form.save(commit=False)
            user_profile.user=user
            user_profile.save()
            return HttpResponseRedirect(reverse('app:login'))
        else: err=1
    else:
        err=0
        sleep(1)
        user_form=UserForm()
        user_profile_form=UserProfileForm()
    return render(request,"sign.html",{"user_form":user_form,"user_profile_form":user_profile_form,"err":err})

'''
is_active
Designates whether this user account should be considered active. We recommend that you set this flag to False 
instead of deleting accounts; that way, if your applications have any foreign keys to users, the foreign keys won’t break.
'''

def login_user(request):
    if(request.method=='POST'):
        username=request.POST['username']
        password = request.POST['password']
        user=authenticate(username=username,password=password)
        if(user):
            login(request,user)
            return HttpResponseRedirect(reverse('app:index'))
        else:
            return render(request,'acc_not_found.html',{})
    else:
        sleep(1)
    return render(request,"login.html",{})

@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('app:index'))

def create(request):
    return render(request,'creator.html',{})

templates/acc_not_found.html
{% extends 'base.html' %}
    {% load static %}
    {% block body %}
    <div class="cont rounded bg-light rounded">
        <div class="grid-card bg-white p-2" style="grid-template-rows:50% 35% 15%">
            <div><img class="rounded" src="{% static 'audit.png' %}" alt="Not-found-img" id="img-001"/></div>
            <h1>Account Not Found or is Inactive</h1>
            <div><a href="{% url 'app:index' %}"><button class="btn btn-primary btn-lg rounded">Home</button></a></div>
        </div>
    </div>
    {% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'login.png' %}"/>
    <!-- bootstrap css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
    crossorigin="anonymous">
    <!-- Local CSS -->
    <link rel="stylesheet" href="{% static 'style.css' %}"/>
    <title>AUTHENTICATION SYSTEM</title>
</head>
<body>
    <div class="progress" style="height:4px;">
        <div class="progress-bar bg-primary w-0"></div>
    </div>
    <nav class="navbar fixed-top navbar-expand-md px-2 rounded bg-dark" style="top:4px;">
        <div class="navbar-header" id="progress-init">
            <a href="/"><img src="{% static 'brand.jpg' %}" class="rounded-pill" style="width:50px;height:50px;" alt="Logo"></a>
        </div>
        <button class="navbar-toggler text-white" data-bs-toggle="collapse" data-bs-target="#mycollapse">
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="mycollapse">
            <div class="container">
                <ul class="navbar-nav">
                    <li class="nav-item" id="progress-init"><a class="nav-link text-white" href="{% url 'admin:index' %}">Admin</a></li>
                    <li class="nav-item" id="progress-init"><a class="nav-link text-white" href="{% url 'app:sign' %}">Sign Up</a></li>
                    {% if user.is_authenticated %}
                    <li class="nav-item" id="progress-init"><a class="nav-link text-white" href="{% url 'app:logout' %}">Logout</a></li>
                    {% else %}
                    <li class="nav-item" id="progress-init"><a class="nav-link text-white" href="{% url 'app:login' %}">Login</a></li>
                    {% endif %}
                    <li class="nav-item dropdown" style="cursor:pointer;">
                        <a class="nav-link text-white dropdown-toggle" data-bs-toggle="dropdown">About</a>    
                        <ul class="dropdown-menu">
                            <li id="progress-init"><a class="dropdown-item" href="{% url 'app:create' %}">Creator</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block body %}
    <!-- Content goes here -->
    {% endblock %}
</body>
<!-- BootStrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" 
crossorigin="anonymous"></script>
<!-- font awesome icons -->
<script src="https://kit.fontawesome.com/2939ec19a4.js" crossorigin="anonymous"></script>
<!-- Local JS -->
<script src="{% static 'script.js' %}"></script>
</html>

templates/creator.html
{% extends 'base.html' %}
    {% load static %}
    {% block body %}
    <div class="cont">
        <div class="grid-card" style="grid-template-rows:15% 55% 25%;transform:translateY(30px);">
            <h1>Anish Kumar</h1>
            <div><img id="img-003" class="img-fluid img-thumbnail" src="{% static 'anish.png' %}" alt="anish_img"/></div>
            <div class="p-2 row">
                <div class="col-sm-4 my-1">
                    <a href="https://www.linkedin.com/in/anish-kumar-4b5771229">
                        <button type="button" class="btn btn-primary">
                            <i class="fa-brands fa-linkedin"></i>&nbsp;LinkedIn
                        </button>
                    </a>
                </div>
                <div class="col-sm-4 my-1">
                    <a href="https://github.com/anish2272002">
                        <button type="button" class="btn btn-dark">
                            <i class="fa-brands fa-github"></i>&nbsp;GitHub
                        </button>
                    </a>
                </div>
                <div class="col-sm-4 my-1">
                    <a href="https://www.instagram.com/anish__72002/">
                        <button type="button" class="btn text-white" style="background:#E1306C;">
                            <i class="fa-brands fa-instagram"></i>&nbsp;Instagram
                        </button>  
                    </a>
                    
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <div class="cont bg-light">
        {% if user.is_authenticated %}
            <div class="grid-card" style="grid-template-rows:20% 65% 15%">
                <div><h3>Welcome</h3><h3>{{user.first_name}} {{user.last_name}}</h3></div>
                <div><img id="img-002" class="img-fluid img-thumbnail rounded m-3" src="{{pic.url}}" alt="Login_img"/></div>
                <div><h3>{{user.username}}</h3><h3>{{user.email}}</h3></div>
            </div>
        {% else %}
        <div class="grid-card" style="transform:translateY(30px);">
            <h1>Welcome</h1>
            <div><img id="img-001" src="{% static 'login.png' %}" alt="Login_img"/></div>
            <h4>This is a Authentication system developed for login and signup.</h3-4>
        </div>
        {% endif %}
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
    {% load static %}
    {% block body %}
    <div class="cont rounded bg-light">
        <div class="grid-card bg-white p-2" style="grid-template-rows:50% 50%;transform:translateY(30px);">
            <div><img class="rounded-circle" src="{% static 'img6Q.png' %}" alt="Login-img" id="img-001"/></div>
            <form method="POST">
                {% csrf_token %}
                <p><input type="text" name="username" class="form-control" placeholder="Username"/></p>
                <p><input type="password" name="password" class="form-control" placeholder="Password"/></p>
                <p><input class="bt btn-success" type="submit" value="Login"></p>
            </form>
        </div>
    </div>
    {% endblock %}

templates/sign.html
{% extends 'base.html' %}
    {% block body %}
    <div class="container bg-light p-3" style="position:relative;top:80px;left:0px;">
        {% if err %}
        <p><div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>Error occured!</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div></p>
        {% else %}
        <p><div class="alert alert-info alert-dismissible fade show" role="alert">
            <strong>Enter data.</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div></p>
        {% endif %}
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{user_form.as_p}}
            {{user_profile_form.as_p}}
            <p><input type="Submit" class="btn btn-primary" value="Register"/></p>
        </form>
    </div>
    {% endblock %}